import type { Metadata } from "next";
import localFont from "next/font/local";
import { Footer } from "@/src/components/layout/Footer";
import { Nav } from "@/src/components/layout/Nav";
import "./globals.css";
import { Providers } from "./providers";

const outfit = localFont({
  src: "../public/fonts/outfit/OutfitVariableFont_wght1.ttf",
  variable: "--font-outfit",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} h-full antialiased`}>
      <body className="min-h-full bg-zinc-50 dark:bg-black">
        <Providers>
          <div className="relative flex min-h-full flex-col">
            <Nav />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
